"""Exception hierarchy for structured output (BAML, etc.) errors.

Provides specific, user-friendly exception types so that common problems
(version mismatches, missing functions, client load failures) produce a
clear message instead of a generic ``ValueError`` buried under a deep
Prefect traceback.

Example:
    ```python
    from genai_tk.extra.structured.exceptions import BamlVersionMismatchError

    try:
        load_baml_client("default")
    except BamlVersionMismatchError as exc:
        print(exc)  # BAML version mismatch: generated with 0.220.0 but 0.222.0 installed ...
    ```
"""

from __future__ import annotations


class StructuredOutputError(Exception):
    """Base exception for structured output errors (BAML, etc.)."""


class BamlError(StructuredOutputError):
    """Base exception for BAML-related errors."""


class BamlVersionMismatchError(BamlError):
    """BAML client was generated with a different version of baml-py than is installed.

    The baml_client code was generated by the BAML CLI at ``generator_version``,
    but the installed ``baml-py`` library is at ``library_version``.
    """

    def __init__(
        self,
        generator_version: str | None = None,
        library_version: str | None = None,
        raw_message: str = "",
    ) -> None:
        self.generator_version = generator_version
        self.library_version = library_version
        self.raw_message = raw_message

        if generator_version and library_version:
            message = (
                f"BAML version mismatch: baml_client was generated with baml-py {generator_version} "
                f"but {library_version} is installed.\n"
                f"Fix: uv add baml-py=={generator_version}   (or regenerate: baml generate)"
            )
        elif raw_message:
            message = f"BAML version mismatch: {raw_message}"
        else:
            message = "BAML version mismatch between baml_client generator and installed baml-py"

        super().__init__(message)


class BamlClientLoadError(BamlError):
    """Failed to load the BAML client modules for a given config."""

    def __init__(
        self,
        config_name: str,
        reason: str,
        original_error: Exception | None = None,
    ) -> None:
        self.config_name = config_name
        self.original_error = original_error
        super().__init__(f"Failed to load BAML client for config '{config_name}': {reason}")


class BamlFunctionNotFoundError(BamlError):
    """The requested BAML function does not exist in the async client."""

    def __init__(self, function_name: str, config_name: str | None = None) -> None:
        self.function_name = function_name
        self.config_name = config_name
        ctx = f" (config: {config_name})" if config_name else ""
        super().__init__(f"BAML function '{function_name}' not found in client{ctx}")


class BamlInvocationError(BamlError):
    """A BAML function call failed at runtime."""

    def __init__(self, function_name: str, reason: str, original_error: Exception | None = None) -> None:
        self.function_name = function_name
        self.original_error = original_error
        super().__init__(f"BAML function '{function_name}' failed: {reason}")
